### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by engalaaodeh** [zGrav/xtream-iptv-player#1]
hello,

First i need to thank you for your effort and I used extreme code version 1.0.44 and 1.0.60 and when try to connect
have error fetching data please to help me to solve this issue ASAP.

my server : http://173.249.31.8:8000/
user : alaa
pass : alaa

**Comment by zGrav** [comment]
Hey,

I‘ll give this a look in a bit.

Have you also tried the reactnative version?

**Comment by engalaaodeh** [comment]
Hey,

Yes sure I used reactnative version

Regards


Eng. Alaa Odeh

Expert IT Business Solution
ITN – ITO \ Infrastructure Systems

Jordan Telecom Group
P.O.  Box  1689 -1118 Amman
Hashemite Kingdom of Jordan

M:    + 962 (0) 776598229
F:     + 962 (0) 64 60 62 16

@ :  alaa.odeh@orange.com<mailto:alaa.odeh@orange.com>

[cid:image002.jpg@01D3C5E9.1FC67CF0]

**Comment by engalaaodeh** [comment]
yes same issues

please i am very interested https://github.com/zGrav/xtream-iptv-player on this layer but connection failed please your kindly support :)
________________________________________

**Comment by zGrav** [comment]
I have dropped you an email 👍

**Comment by zGrav** [comment]
Non-issue, closing.
