### ISSUE TITLE
android support

### ISSUE THREAD

**Issue by catalinx3006** [zGrav/xtream-iptv-player#2]
hi, thank you for your project, i would like to ask if it can be used on android 4.2
Thanks,
Regards, Catalin

**Comment by zGrav** [comment]
Hey,

Sadly only from Android 5 and above :(

Regards,
David

**Comment by zGrav** [comment]
@catalinx3006 this one is Android 4.4

https://github.com/zGrav/xtream-iptv-player-reactnative
